RIGHT          seek  2 exact
LEFT           seek -2 exact
WHEEL_UP       add volume 2
WHEEL_DOWN     add volume -2
UP             add volume 2
DOWN           add volume -2
h script-binding memo-history
g script-binding toggle-gpu-effects